Add work command
nightlyOrg/nightly-bot pull request #26
Opened 2023-05-12 20:26 UTC by ToothyDev

Includes several jobs with an upper and lower pay bracket, failure chances and custom failure messages for each job. The option inside discord gets autocompleted so all jobs are visible to the user.
I could add picking a random job in case the user doesn't specify a job to use, please let me know

2023-05-15 07:25 UTC, MiataBoy requested changes

2023-05-15 07:25 UTC, JoshuaSlui commented on cogs/currency.py
> +            await modifyData('UPDATE economy SET CASH = CASH + %s WHERE UID = %s', [pay, ctx.author.id])
Please use `ON DUPLICATE KEY` instead. That would spare you two unnecessary database calls.

2023-05-15 07:25 UTC, MiataBoy commented on cogs/currency.py
> +            return await ctx.respond(f"{utilities.data.Emotes.crossmark} {work.fail_message}")
Please use `Emotes.crossmark`.

2023-05-15 07:25 UTC, JoshuaSlui commented on cogs/currency.py
> +import utilities.data
This was already imported in a more efficient manner on line 6.

2023-05-15 07:25 UTC, JoshuaSlui commented on cogs/currency.py
> +            return await ctx.respond(f"{utilities.data.Emotes.checkmark} You did your job well!\nPay: {pay} {utilities.data.Emotes.cash}")
Please use `Emotes.checkmark` and `Emotes.cash`.

2023-05-15 12:05 UTC, ToothyDev commented on cogs/currency.py
> +            await modifyData('UPDATE economy SET CASH = CASH + %s WHERE UID = %s', [pay, ctx.author.id])
Not quite sure how to use that in this scenario. Would I need to always run the second line, and then add ON DUPLICATE KEY to actually modify the cash if the user already has an entry?

2023-05-15 12:07 UTC, MiataBoy commented on cogs/currency.py
> +            await modifyData('UPDATE economy SET CASH = CASH + %s WHERE UID = %s', [pay, ctx.author.id])
You can see usage of it in the `daily` command.

2023-05-15 12:07 UTC, MiataBoy commented
Please mind the merge conflict too^

2023-05-17 20:52 UTC, MiataBoy requested changes
Move jobs.py to the utilities folder and we're good.

2023-05-17 20:52 UTC, MiataBoy requested changes
Move jobs.py to the utilities folder and we're good.

2023-05-17 20:57 UTC, MiataBoy approved these changes

2023-05-17 20:58 UTC, merged